version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ../.env
  web:
    image: menyanet73/ndvi_api:v09.06.22
    restart: always
    volumes:
      - static_value:/app/static
      - media_value:/app/media
    depends_on:
      - db
    env_file:
      - ../.env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - static_value:/var/html/static
      - media_value:/var/html/media/
    depends_on:
      - web
volumes:
  static_value:
  media_value: